name: Update JSON Index

# 给 Actions 写权限
permissions:
  contents: write

on:
  workflow_dispatch:      # 手动触发
  schedule:               # 定时触发，可选
    - cron: '0 0 * * *'   # 每天 0 点执行
  push:
    branches: [ main ]    # 当 main 有推送时执行

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure git identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Generate publicFileIndex.json
        run: |
          # 在这里调用你生成 publicFileIndex.json 的脚本
          # 例如：node scripts/genIndex.js
          echo "这里写生成 JSON 的命令"

      - name: Commit & Push if changed
        run: |
          git add publicFileIndex.json
          if ! git diff --cached --quiet; then
            git commit -m '由Actions自动生成插件市场所需JSON索引'
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/jingshui-git/bncr.git
            git push
          else
            echo "publicFileIndex.json 没有变化，跳过提交"
          fi
