name: Update JSON Index

# 赋予 Actions 写权限
permissions:
  contents: write

# 触发条件：手动、main分支推送、定时
on:
  workflow_dispatch:       # 手动运行
  push:
    branches:
      - main               # main 分支更新时运行
  schedule:
    - cron: '0 0 * * *'    # 每天零点自动运行（可选）

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 配置 git 用户信息
      - name: Configure git identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      # 3. 生成 publicFileIndex.json（替换成你的生成脚本）
      - name: Generate publicFileIndex.json
        run: |
          echo "这里运行你生成 JSON 的脚本"
          # 例如：node scripts/genIndex.js

      # 4. 有修改才提交并推送
      - name: Commit & Push if changed
        run: |
          git add publicFileIndex.json
          if ! git diff --cached --quiet; then
            git commit -m '由Actions自动生成插件市场所需JSON索引'
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/jingshui-git/bncr.git
            git push
          else
            echo "publicFileIndex.json 没有变化，跳过提交"
          fi
